### ISSUE TITLE
compatibility with levelup

### ISSUE THREAD

**Issue by wanderer** [wanderer/merkle-patricia-tree#2]
it should have nearly the same api as levelup

**Comment by wanderer** [comment]
we cannot do this because of the extra methods needed by trie

**Comment by deanlandolt** [comment]
I can't quite see how this would be incompatible -- couldn't it be a superset of the levelup api? The `batch` API would probably need to be renamed, or at least augmented to also take a levelup-style ops array, and perhaps return a chained batch instance when called w/ `arguments.length === 0` (though IMHO that's not strictly necessary).

The other incompatibility is in `createReadStream` -- ISTM it should accept at least the `ltgt` options (maybe foregoing `reverse` if that's too much trouble).

Would you take a patch?
